### ISSUE TITLE
Creating/Loading a large arena causes the server to run out of CPU and Memory.

### ISSUE THREAD

**Issue by imxari** [Simplicitee/ProjectArenas#2]
If you use a large arena when you try to create, load or restore the arena the serve runs out of cpu and memory which causes it to crash. I can see you're running stuff async off the main thread but, would it be possible to instead of holding all the blocks in memory write/load in each block from the file as it is needed?

**Comment by Simplicitee** [comment]
I tried a version of the plugin with that and it was much slower to reload arenas. IO operations just inherently are more expensive to do, so repeating the reading from the file for each step of the reload results in a much slower reload speed. It sounds good in theory but doesn't work so well in practice.
